# Generated by Django 4.2.7 on 2023-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('programme', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='unknown', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('program', models.CharField(max_length=10)),
                ('semester', models.IntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('profilePic', models.ImageField(null=True, upload_to='settings.MEDIA_ROOT')),
                ('loginDate', models.DateTimeField(null=True)),
            ],
        ),
    ]
