# Generated by Django 4.2.7 on 2023-12-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='userName',
            new_name='username',
        ),
    ]
