# Generated by Django 4.2.7 on 2023-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_rename_username_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='programme',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(max_length=30),
        ),
    ]
