# Generated by Django 4.2.7 on 2023-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_faculty_programme_alter_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semail', models.EmailField(max_length=254, unique=True)),
                ('fname', models.EmailField(max_length=254, unique=True)),
                ('q1', models.CharField(max_length=2)),
                ('q2', models.CharField(max_length=2)),
                ('q3', models.CharField(max_length=2)),
                ('q4', models.CharField(max_length=2)),
                ('q5', models.CharField(max_length=2)),
                ('q6', models.CharField(max_length=2)),
                ('q7', models.CharField(max_length=2)),
                ('q8', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
