# Generated by Django 4.2.7 on 2023-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_feedback_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='semail',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q8',
            field=models.IntegerField(),
        ),
    ]
