# Generated by Django 4.2.7 on 2023-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_remove_feedback_fname_remove_feedback_semail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(default=True, upload_to='static/'),
        ),
    ]
