# Generated by Django 4.2.7 on 2023-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_faculty_pic_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(default=True, upload_to='static'),
        ),
    ]
